@PokemonProxy_HostAddress = https://localhost:5225
@pokemonName = pikachu

GET {{PokemonProxy_HostAddress}}/pokemon/{{pokemonName}}
Accept: application/json

###

GET {{PokemonProxy_HostAddress}}/translated/pokemon/{{pokemonName}}
Accept: application/json

###
